global:
  imagePullPolicy: Always
  images:
    confserver: curiefense/confserver
    curielogger: curiefense/curielogger
    curietasker: curiefense/curietasker
    logdb: curiefense/logdb
    redis: curiefense/redis
    curielogserver: curiefense/curielogserver
    uiserver: curiefense/uiserver
    curiesync: curiefense/curiesync
    grafana: curiefense/grafana
    prometheus: curiefense/prometheus

  storage:
    # use the default storage class if null
    storage_class_name: null
    confserver_storage_size: '1Gi'
    grafana_storage_size: '1Gi'
    logdb_storage_size: '10Gi'
    prometheus_storage_size: '1Gi'
    redis_storage_size: '1Gi'

  settings:
    curieconf_manifest_url: 's3://curiefense-test01/prod/manifest.json'
    curiefense_db_hostname: 'logdb'
    # supported types: 's3', 'gs'
    curiefense_bucket_type: 's3'
    # will be overridden if deploy.sh is used
    docker_tag: 'latest'

  requests:
    cpu:
      curielogger: "100m"
      redis: "10m"
      logstash: "100m"
      kibana: "100m"
      logdb: "1"
      uiserver: "100m"
      confserver_init: "100m"
      confserver_nginx: "10m"
      confserver_uwsgi: "100m"
      curietasker: "100m"
      prometheus: "100m"
      grafana: "20m"
      curielogserver_nginx: "10m"
      curielogserver_uwsgi: "10m"
      elasticsearch: "1"

  enable:
    # set to false to disable parts of this deployment, ex. if you prefer to use your own versions
    grafana: true
    prometheus: true
    # postgres database to store logs. Can be replaced with AWS Aurora
    logdb: true
