{{- if eq .Values.global.settings.curiefense_logdb_type "elasticsearch" }}
---
# a headless service is required for StatefulSets
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: elasticsearch
  name: elasticsearch-hl
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  clusterIP: None
  selector:
    app.kubernetes.io/name: elasticsearch
{{- end }}
