{{- if eq .Values.global.settings.curiefense_logdb_type "elasticsearch" }}
{{- if eq .Values.global.enable.elasticsearch }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: elasticsearch
  name: elasticsearch
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  selector:
    app.kubernetes.io/name: elasticsearch
{{ end }}
{{ end }}
