{{- if eq .Values.global.settings.curiefense_logdb_type "elasticsearch" }}
{{- if eq .Values.global.settings.curiefense_es_forwarder "fluentd" }}
{{- if eq .Values.global.enable.fluentd }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: fluentd
  name: fluentd
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fluentd
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluentd
    spec:
      containers:
      - name: fluentd
        env:
        - name: ELASTICSEARCH_HOSTS
          value: {{ .Values.global.settings.curiefense_es_hosts }}
        image: fluent/fluentd:v1.12.0-1.0
        ports:
        - containerPort: 5001
          name: fluentd-http
        livenessProbe:
          tcpSocket:
            port: fluentd-tcp
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        volumeMounts:
        - name: fluentd-config
          mountPath: "/fluentd/etc"
          readOnly: true
        resources:
          limits:
            memory: "500Mi"
            cpu: "900m"
          requests:
            memory: "20Mi"
            cpu: "100m"
      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-configmap
          items:
            - key: fluent.conf
              path: fluent.conf
      restartPolicy: Always
      serviceAccountName: ""
{{- if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
