{{- if eq .Values.global.settings.curiefense_logdb_type "postgres" }}
{{- if .Values.global.enable.logdb }}
---
# a headless service is required for StatefulSets
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: logdb
  name: logdb-hl
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "postgres"
    port: 5432
    targetPort: 5432
  clusterIP: None
  selector:
    app.kubernetes.io/name: logdb
{{ end }}
{{ end }}
