---
# a headless service is required for StatefulSets
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: logdb
  name: logdb-hl
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  clusterIP: None
  selector:
    app.kubernetes.io/name: logdb
