{{- if eq .Values.global.settings.curiefense_logdb_type "elasticsearch" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: {{ .Release.Namespace }}
data:
  logstash.conf: |-
    input {
        tcp {
            port => 5000
        }
        http {
            port => 5001
        }
    }
    output {
        elasticsearch {
            hosts => "elasticsearch:9200"
            index => "curieaccesslog"
        }
    }
{{- end }}
