{{- if eq .Values.global.settings.curiefense_logdb_type "elasticsearch" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: logstash
  name: logstash
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: logstash
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: logstash
    spec:
      containers:
      - name: logstash
        env:
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch:9200
        image: docker.elastic.co/logstash/logstash:7.10.1
        ports:
        - containerPort: 5000
          name: logstash-tcp
        - containerPort: 5001
          name: logstash-http
        livenessProbe:
          tcpSocket:
            port: logstash-tcp
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        volumeMounts:
        - name: logstash-config
          mountPath: "/usr/share/logstash/pipeline"
          readOnly: true
        resources:
          limits:
            memory: "500Mi"
            cpu: "900m"
          requests:
            memory: "20Mi"
            cpu: "100m"
      volumes:
      - name: logstash-config
        configMap:
          name: logstash-configmap
          items:
            - key: logstash.conf
              path: logstash.conf
      restartPolicy: Always
      serviceAccountName: ""
{{- if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
{{- end }}
{{- end }}
